name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, gd
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install npm dependencies
      run: npm install

    - name: Build front-end assets
      run: npm run build
    - name: Copy .env
      run: cp .env.example .env

    - name: Generate key
      run: php artisan key:generate

    - name: Set up database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run migrations and seeders
      env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
      run: php artisan migrate --seed

    - name: Run tests
      env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit --coverage-text

